#### 0. Setup Worksapce ####
graphics.off()
rm(list=ls())
library(tidyverse)

# datasets, like functions require their containing libraries to be loaded

# linear model
m <- lm(mpg$cty ~ mpg$displ)
# Scatter plot
plot(mpg$displ, mpg$cty,
     xlab = "Engine displacement (Liters)",
     ylab = "City mileage (mpg)",
     xlim = c(0,max(mpg$displ)+1),
     ylim = c(0, max(mpg$cty)+5))

# overlay the line of best fit generated by the linear regression model
abline(m, col="red")

# Summary of model
summary(m)
